import { Provider } from "mobx-react";
import { observable } from "mobx";
import * as React from "react";
import ReactDOM from "react-dom";
import { act } from "react-dom/test-utils";
import { MemoryRouter } from "react-router-dom";
import { StyleSheetManager, ThemeProvider } from "styled-components";
import { light } from "@shared/styles/theme";
import Sidebar from "./Sidebar";
import ToggleButton from "./components/ToggleButton";

// These pull in Radix packages whose ESM builds can't resolve React 17's
// jsx-runtime under Vitest. None of them affect the sidebar's own styles.
vi.mock("@radix-ui/react-direction", () => ({ useDirection: () => "ltr" }));
vi.mock("../TooltipContext", () => ({
  TooltipProvider: ({ children }: { children: React.ReactNode }) => children,
}));
vi.mock("~/menus/AccountMenu", () => ({ default: () => null }));
vi.mock("../Notifications/NotificationsPopover", () => ({
  default: () => null,
}));
vi.mock("../Notifications/NotificationIcon", () => ({ default: () => null }));
vi.mock("~/components/Avatar", () => ({ Avatar: () => null }));

// A distinctive width so assertions prove the value comes from the theme
// rather than a hardcoded number.
const COLLAPSED_WIDTH = 40;
const theme = { ...light, sidebarCollapsedWidth: COLLAPSED_WIDTH };

/** The generated class selector for ToggleButton, e.g. ".sc-abc123". */
const toggleButtonSelector = ToggleButton.toString();

/** The rule that keeps the toggle button's row visible while collapsed. */
const toggleRowSelector = `:not(:focus-within) > div:has(${toggleButtonSelector})`;

type UiState = {
  sidebarWidth: number;
  sidebarIsClosed: boolean;
  mobileSidebarVisible: boolean;
};

function createStores(state: Partial<UiState> = {}) {
  const ui = observable({
    sidebarWidth: light.sidebarWidth,
    sidebarIsClosed: false,
    mobileSidebarVisible: false,
    ...state,
    set(values: Partial<UiState>) {
      Object.assign(ui, values);
    },
    setSidebarResizing() {},
    hideMobileSidebar() {},
    toggleMobileSidebar() {},
    collapseSidebar() {},
  });
  return { ui, auth: { user: undefined } };
}

/**
 * Collects the CSS text of every rule (including those nested in media
 * queries) in the given style target whose selector references one of the
 * element's class names. Whitespace is collapsed to single spaces.
 */
function cssFor(element: Element, styleTarget: HTMLElement): string {
  const classNames = Array.from(element.classList);
  const matches: string[] = [];

  const walk = (rules: CSSRuleList) => {
    for (const rule of Array.from(rules)) {
      if ("selectorText" in rule) {
        const { selectorText } = rule as CSSStyleRule;
        if (classNames.some((name) => selectorText.includes(`.${name}`))) {
          matches.push(rule.cssText);
        }
      } else if ("cssRules" in rule) {
        walk((rule as CSSGroupingRule).cssRules);
      }
    }
  };

  for (const style of Array.from(styleTarget.querySelectorAll("style"))) {
    if (style.sheet) {
      walk(style.sheet.cssRules);
    }
  }
  return matches.join("\n").replace(/\s+/g, " ");
}

describe("Sidebar", () => {
  let container: HTMLDivElement;
  let styleTarget: HTMLDivElement;

  beforeEach(() => {
    // The global mock returns a plain string, which useMediaQuery can't
    // subscribe to. Report a desktop-sized viewport instead.
    window.matchMedia = ((query: string) => ({
      matches: false,
      media: query,
      addEventListener: () => {},
      removeEventListener: () => {},
    })) as unknown as typeof window.matchMedia;
    vi.spyOn(document, "hasFocus").mockReturnValue(true);

    container = document.createElement("div");
    document.body.appendChild(container);
    // A fresh stylesheet per test, so rules generated by earlier renders
    // can't make assertions pass by accident.
    styleTarget = document.createElement("div");
    document.head.appendChild(styleTarget);
  });

  afterEach(() => {
    ReactDOM.unmountComponentAtNode(container);
    container.remove();
    styleTarget.remove();
    vi.restoreAllMocks();
  });

  function render(
    state: Partial<UiState>,
    props: { hidden?: boolean; canCollapse?: boolean } = {}
  ) {
    const stores = createStores(state);
    act(() => {
      ReactDOM.render(
        <Provider rootStore={stores}>
          <StyleSheetManager target={styleTarget}>
            <ThemeProvider theme={theme}>
              <MemoryRouter>
                <Sidebar {...props}>
                  <div>
                    <span>Team name</span>
                    <ToggleButton
                      position="bottom"
                      title=""
                      image={<span />}
                      onClick={() => {}}
                    />
                  </div>
                  <div>Other content</div>
                </Sidebar>
              </MemoryRouter>
            </ThemeProvider>
          </StyleSheetManager>
        </Provider>,
        container
      );
    });
    const sidebar = document.getElementById("sidebar");
    if (!sidebar) {
      throw new Error("Sidebar did not render");
    }
    return { sidebar, css: () => cssFor(sidebar, styleTarget) };
  }

  describe("collapsed strip width", () => {
    it("leaves a strip the width of theme.sidebarCollapsedWidth on screen", () => {
      const css = render({ sidebarIsClosed: true }).css();

      expect(css).toContain(`translateX(calc(-100% + ${COLLAPSED_WIDTH}px))`);
    });

    it("uses the same strip width for right-to-left layouts", () => {
      const css = render({ sidebarIsClosed: true }).css();

      expect(css).toContain(`translateX(calc(100% - ${COLLAPSED_WIDTH}px))`);
    });

    it("no longer uses the old hardcoded 8px or 16px strip", () => {
      const css = render({ sidebarIsClosed: true }).css();

      expect(css).not.toContain("calc(-100% + 16px)");
      expect(css).not.toContain("calc(-100% + 8px)");
      expect(css).not.toContain("calc(100% - 8px)");
    });

    it("is not translated when the sidebar is open", () => {
      const css = render({ sidebarIsClosed: false }).css();

      expect(css).not.toContain(`${COLLAPSED_WIDTH}px)`);
      expect(css).toContain("translateX(0)");
    });

    it("is not collapsed when collapsing is disabled", () => {
      const css = render(
        { sidebarIsClosed: true },
        { canCollapse: false }
      ).css();

      expect(css).not.toContain(`${COLLAPSED_WIDTH}px)`);
    });
  });

  describe("toggle button while collapsed", () => {
    it("keeps the toggle button and its row visible", () => {
      const css = render({ sidebarIsClosed: true }).css();

      expect(css).toContain(`${toggleRowSelector} {opacity: 1;}`);
      expect(css).toContain(
        `${toggleRowSelector} ${toggleButtonSelector} {opacity: 1;}`
      );
    });

    it("fades out the rest of the toggle button's row", () => {
      const css = render({ sidebarIsClosed: true }).css();

      expect(css).toContain(
        `${toggleRowSelector} > :not(:has(${toggleButtonSelector})) {opacity: 0;`
      );
    });

    it("does not apply when the sidebar is open", () => {
      const css = render({ sidebarIsClosed: false }).css();

      expect(css).not.toContain(toggleRowSelector);
    });

    it("does not apply when collapsing is disabled", () => {
      const css = render(
        { sidebarIsClosed: true },
        { canCollapse: false }
      ).css();

      expect(css).not.toContain(toggleRowSelector);
    });

    it("does not apply while the sidebar content is hidden", () => {
      const css = render({ sidebarIsClosed: true }, { hidden: true }).css();

      expect(css).not.toContain(toggleRowSelector);
    });

    it("does not apply while hovering reveals the sidebar", () => {
      const { sidebar, css } = render({ sidebarIsClosed: true });
      expect(css()).toContain(toggleRowSelector);

      act(() => {
        sidebar.dispatchEvent(
          new MouseEvent("pointermove", { bubbles: true, buttons: 0 })
        );
      });

      expect(css()).not.toContain(toggleRowSelector);
    });
  });
});
